backend:
  name: github
  repo: your-github-username/your-repo-name  # GitHub repo নাম বসাও
  branch: main  # অথবা master যদি তোমার main branch নাম master হয়
  auth_type: implicit  # OAuth popup style, identity লাগবে না
  open_authoring: true # visitor contribution enable করতে
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["সারাদেশ", "রাজনীতি", "খেলাধুলা", "আন্তর্জাতিক", "বিনোদন"] }
      - { label: "Top News", name: "top_news", widget: "boolean", default: false }
      - { label: "Image", name: "image", widget: "image" }
